name: Validate DB Script

on:
  pull_request

jobs:
  validate-sql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate SQL scripts
        run: |
          for file in scripts/*.sql; do
            echo "Validating $file"

            # Verifica o nome do arquivo
            # filename=$(basename "$file")
            # if [[ ! "$filename" =~ ^[0-9]{14}\.sql$ ]]; then
            #   echo "❌ Nome inválido: $filename. Use o formato YYYYmmddhhmmss.sql"
            #   exit 1
            # fi

            # Verifica o comentário inicial
            head -n 2 "$file" | grep -q "Ticket:" || { echo "❌ Faltando comentário 'Ticket:' no início do arquivo."; exit 1; }
            head -n 2 "$file" | grep -q "Network:" || { echo "❌ Faltando comentário 'Network:' no início do arquivo."; exit 1; }

            # Verifica se comandos estão em uppercase
            if grep -Eiq '\bselect\b|\bfrom\b|\bwhere\b' "$file"; then
              echo "❌ Comandos SQL devem estar em UPPERCASE (SELECT, FROM, WHERE)"
              exit 1
            fi

            # Verifica nomes de tabela camelCase
            if grep -Eq 'create table [a-z]*[A-Z]' "$file"; then
              echo "❌ Nome de tabela com camelCase encontrado."
              exit 1
            fi

            # Verifica primary key
            if grep -Eq '\bId_[a-zA-Z]+' "$file"; then
              echo "❌ Primary key 'Id' não pode ser seguido de underscore."
              exit 1
            fi

          done

          echo "✅ Todas as validações passaram!"
